Repository MoisesGzz92/TaskManager_SW-testing, pull requests merged in 2024-11, with the labels that each got.

#4 Gruppe 3
  features/get_task.feature
  features/steps/get_task_steps.py
  taskmanager/app/task_manager.py
Labels: enhancement, testing

#9 Integrated Unit Test for our Task_Manager derived from yesterday's session
  taskmanager/__init__.py
  taskmanager/app/__init__.py
  taskmanager/app/task_manager.py
  taskmanager/tests/test_taskmanager.py
Labels: enhancement, testing

#10 Add first version of the Flask REST API server
  doc/api.md
  doc/assets/api_reference.jpeg
  doc/assets/task_manager_api.jpeg
  doc/session6-14-11-24.md
  doc/session7-12-11-24.md
  requirements.txt
  taskmanager/app/api.py
Labels: documentation, enhancement

#11 fixed curl examples to latest api definition
  doc/api.md
Labels: bug, documentation

#14 Erledigt: Gruppe 3
  doc/api.md
  taskmanager/app/api.py
Labels: enhancement

#13 added api route for update_task
  taskmanager/app/api.py
Labels: enhancement

#15 changed task related api url paths from 'tasks' to 'task'
  taskmanager/app/api.py
Labels: enhancement
